### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by ahwagner** [iobio/iobio.viz#4]
What are the license terms for this repository? I didn't notice a LICENSE file in this repo or https://github.com/iobio/iobio.js. There **is** a license file at Minion (https://github.com/iobio/minion/blob/master/LICENSE), but it's empty.

I will be building an application that would benefit from some of these visualizations, but I don't want to start using any existing code if the license omission is an implicit exclusive copyright. On the other hand, if this is intended to be licensed under the [MIT license](https://choosealicense.com/licenses/mit/), that would be *amazing*...

**Comment by chmille4** [comment]
Just added a MIT license, please feel free to use :)

Also, if you feel like telling us a bit more about what you are building, you can email me at my profile email address. We are always curious to see what people are building.
